CREATE TABLE ADVENTURE_TRIP (
    TRIP_ID INTEGER PRIMARY KEY,
    TRIP_NAME TEXT NOT NULL,
    START_LOCATION TEXT,
    STATE TEXT,
    DISTANCE REAL,
    MAX_GRP_SIZE INTEGER,
    TYPE TEXT,
    SEASON TEXT
);

-- Insert sample data for Problem 3
INSERT INTO ADVENTURE_TRIP VALUES (45, 'John Doe', 'John', 'US', 8, 8, 'Hiking', 'Summer');
